/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatLightLaf;
import dao.daoServicios;
import dao.daoTrabajador;
import java.awt.Color;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelo.Servicioadmin;
import modelo.Servicios;
import modelo.Trabajador;
import modelo.Usuario;

/**
 *
 * @author Adria
 */
public class AdminTrabajador extends javax.swing.JPanel {

     DefaultTableModel model = new DefaultTableModel();
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
    int validacion;     
    daoTrabajador X=new daoTrabajador();
    public AdminTrabajador() {
         FlatLightLaf.setup();
        initComponents();
        btnupdate.setEnabled(false);
        tabla.setModel(model);
        model.addColumn("IDTRABAJADOR");
        model.addColumn("CODIGO");
        model.addColumn("CONTRASEÑA");
        model.addColumn("DNI");
        model.addColumn("ESPECIALIDAD");
        model.addColumn("NOMBRE");
        model.addColumn("APELLDIO");       
        model.addColumn("SEXO");
        model.addColumn("TELEFONO");
        model.addColumn("EMAIL");
        juser.setText("");     
        jdni.setText("");
        jcorreo.setText("");
        txtnumeroayuda.setText("");
        btndelete.setEnabled(false);
        btnupdate.setEnabled(false);
        cb_sexo.addItem("HOMBRE");
        cb_sexo.addItem("MUJER");
        X.Iniciartabla(model);
        txtcodigo.setText(X.generarCodigoEspecialidad()); 
        actualizarTabla();
        btndelete.setEnabled(false);
        btnupdate.setEnabled(false);
         comboServiciosListar();
    }
        public void comboServiciosListar(){
            daoServicios daoServ=new daoServicios();
        List<Servicioadmin> listaServicios = daoServ.obtenerServicios2();
        for (Servicioadmin servicio : listaServicios) {
            cb_servicio.addItem(servicio.getNombre_servicio());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtuser = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcontra = new javax.swing.JTextField();
        txtnumero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cb_sexo = new javax.swing.JComboBox<>();
        cb_servicio = new javax.swing.JComboBox<>();
        txtcorreo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnnew = new javax.swing.JButton();
        juser = new javax.swing.JLabel();
        jdni = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        jcorreo = new javax.swing.JLabel();
        txtnumeroayuda = new javax.swing.JLabel();
        txtbusqueda = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("CRUD TRABAJADOR");

        jLabel2.setText("CODIGO");

        jLabel3.setText("USUARIO");

        jLabel4.setText("NOMBRE");

        txtcodigo.setEditable(false);

        txtuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtuserKeyReleased(evt);
            }
        });

        jLabel5.setText("APELLIDO");

        jLabel6.setText("CONTRASEÑA");

        txtnumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnumeroFocusLost(evt);
            }
        });
        txtnumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnumeroKeyReleased(evt);
            }
        });

        jLabel7.setText("TELEFONO");

        jLabel8.setText("SEXO");

        jLabel9.setText("CORREO");

        jLabel10.setText("ESPECIALIZACION");

        txtcorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcorreoFocusLost(evt);
            }
        });
        txtcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcorreoKeyReleased(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        btnadd.setText("AÑADIR");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setText("ACTUALIZAR");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setText("ELIMINAR");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnnew.setText("NUEVO");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });

        juser.setText("juser");

        jdni.setText("jdni");

        jLabel12.setText("DNI");

        txtdni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdniKeyReleased(evt);
            }
        });

        jcorreo.setText("jcorreo");

        txtnumeroayuda.setText("telefono");

        txtbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbusquedaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbusquedaKeyTyped(evt);
            }
        });

        jLabel11.setText("BUSQUEDA:");

        jButton1.setText("XCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(juser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(txtuser)
                            .addComponent(txtnombre))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12)
                            .addComponent(jdni))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcontra)
                            .addComponent(txtapellido)
                            .addComponent(txtdni))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnumeroayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtcorreo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(cb_servicio, 0, 84, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jcorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(360, 360, 360))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnupdate)
                        .addGap(71, 71, 71)
                        .addComponent(btnnew, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdni)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtcontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(juser)
                    .addComponent(jcorreo)
                    .addComponent(txtnumeroayuda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(cb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnadd)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btndelete)
                        .addComponent(jButton1)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnupdate)
                    .addComponent(btnnew))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
   public boolean validarletra(String letra){
    return letra.matches("^[a-zA-Z\\s]+$");
    }
    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        btnadd.setEnabled(false);
        btndelete.setEnabled(true);
        btnupdate.setEnabled(true);
        int filaSeleccionadaModelo = tabla.getSelectedRow();
        int filaSeleccionada = sorter.convertRowIndexToModel(filaSeleccionadaModelo);
        System.out.println("FILA"+filaSeleccionada);
            String id = (model.getValueAt(filaSeleccionada, 0).toString());
            String codigo = (model.getValueAt(filaSeleccionada, 1).toString());
            String contra = (model.getValueAt(filaSeleccionada, 2).toString());
            String dni = (model.getValueAt(filaSeleccionada, 3).toString());
            String espe = (model.getValueAt(filaSeleccionada, 4).toString());
            String nombre = (model.getValueAt(filaSeleccionada, 5).toString());
            String apellido = (model.getValueAt(filaSeleccionada, 6).toString());  
            String sexo = (model.getValueAt(filaSeleccionada, 7).toString());     
            String telefono = (model.getValueAt(filaSeleccionada, 8).toString());
            String mail = (model.getValueAt(filaSeleccionada, 9).toString());
                String numeroString = "51" +telefono; 
        if(cb_sexo.equals("HOMBRE"))        {
            cb_sexo.setSelectedItem("HOMBRE");
        }else{
            cb_sexo.setSelectedItem("MUJER");
        }
            txtcodigo.setText(id);
            txtuser.setText(codigo);
            txtnombre.setText(nombre );
            txtapellido.setText(apellido );
            txtdni.setText(dni);
            txtcorreo.setText(mail);
            txtnumero.setText(numeroString);
            txtcontra.setText(contra);


    }//GEN-LAST:event_tablaMouseClicked
    private boolean esNumeroEntero(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
        private void validarNumeroEntero() {
        String cadena = txtnumero.getText();
        if (esNumeroEntero(cadena)) {
        } else {
       JOptionPane.showMessageDialog(null, "SOLO SE DEBE INGRESAR NUMEROS");
       txtnumero.setText("");
        }
    }
    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String nombre,id,dni,contra,servicio,usuario,apellido,numero,sexoid,correo,sexo;
        nombre=txtnombre.getText();
        usuario=txtuser.getText();
        dni=txtdni.getText();
        contra=txtcontra.getText();
        apellido=txtapellido.getText();
        correo=txtcorreo.getText();
         servicio=cb_servicio.getSelectedItem().toString();
         id=txtcodigo.getText();
        sexo=cb_sexo.getSelectedItem().toString();
        numero=txtnumero.getText();
        String numeroString = "51" +numero;
        Usuario u=new Usuario();
        Trabajador t=new Trabajador();
        if(sexo.equals("HOMBRE")){
            sexoid="M";
        }else{
            sexoid="F";
        }

        if (!nombre.isEmpty() && !dni.isEmpty() && !usuario.isEmpty() &&
            !contra.isEmpty() && !correo.isEmpty() &&
            !numero.isEmpty()) {

            if(validacion==1){
                if(numeroString.length() == 11){
                    if(esNumeroEntero(numero)){

                      if(validarletra(nombre)==true && validarletra(contra) ){

                        u.setCodiUsua(usuario);
                        u.setPassUsua(contra);
                        u.setTipoUsua("cliente");
                        t.setApelTrab(apellido);
                        t.setCodiEspe(X.ObtenerCodigoXNombre(servicio));
                        t.setCodiUsua(usuario);
                        t.setDniTrab(dni);
                        t.setEmailTrab(correo);
                        t.setNombTrab(nombre);
                        t.setSexoTrab(sexoid);
                        t.setTeleTrab(numeroString);
                        t.setCodiTrab(id);
                        X.crearUsuario(u, t);
                        limpiar();

                        actualizarTabla();

                    }else{
                       System.out.println("INGRESAR SOLO LETRAS PARA EL NOMBRE"); 
                                            }  
                                           }  else{
                        JOptionPane.showMessageDialog(null, "NUMERO DEBE SER NUMERS");

                    }
                }else{
                    JOptionPane.showMessageDialog(null, "NUMERO DEBE SER NUEVO DIGITOS");

                }

            }   else{
                JOptionPane.showMessageDialog(null, "USUARIO YA EXISTENTE");

            }

        }else{
            JOptionPane.showMessageDialog(null,"Todos los campos deben estar completos");

        }

    }//GEN-LAST:event_btnaddActionPerformed
   private void limpiar(){
        txtnombre.setText("");
        txtdni.setText("");
        txtcorreo.setText("");
        txtnumero.setText("");
        txtnumeroayuda.setText("");
        txtcontra.setText("");
        txtuser.setText("");
        juser.setText("");     
        jdni.setText("");
        jcorreo.setText("");
        txtcodigo.setText(X.generarCodigoEspecialidad()); 

    }
   public void actualizarTabla() {
    // Limpiar el modelo
    model.setRowCount(0);

    // Volver a cargar los datos en el modelo
    X.Iniciartabla(model);

    // Notificar al TableRowSorter sobre los cambios en el modelo
    sorter.modelStructureChanged();

    // Obtener el número de filas en la vista del TableRowSorter
    int rowCount = sorter.getViewRowCount();

    // Imprimir información sobre el rango de filas en la vista
    System.out.println("Rango de filas actual: 0 - " + (rowCount - 1));
    System.out.println("Número total de filas en el modelo: " + model.getRowCount());
    
    // Restablecer el modelo en la tabla (puede que no sea necesario en algunos casos)
    tabla.setModel(model);
}
    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed

        String id,usuario,contra,correo,numero,apellido,nombre,dni,tipo;
        nombre=txtnombre.getText();
        apellido=txtapellido.getText();
        usuario=txtuser.getText();
        contra=txtcontra.getText();
        correo=txtcorreo.getText();
        numero=txtnumero.getText();
        id=txtcodigo.getText();
        dni=txtdni.getText();
        String numeroString = "51" +numero;

String tipocuenta = (String) cb_sexo.getSelectedItem();
String espe = (String) cb_servicio.getSelectedItem();
String cpdeespe=X.ObtenerCodigoXNombre(espe);
        tipo="";
        if(tipocuenta.equals("MUJER")){
            tipo="F";
        }else{
                tipo="M";  }

        

        X.actualizarusuario(contra, "trabajador", id, dni, nombre, apellido, numeroString, tipo, correo, cpdeespe, usuario);
        actualizarTabla();
        limpiar();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed

        int filaSeleccionada = tabla.getSelectedRow();
        int filaSeleccionadaModelo = sorter.convertRowIndexToModel(filaSeleccionada);

        System.out.println("fila"+filaSeleccionadaModelo);
        String  usuario = (txtuser.getText());
        System.out.println("ID ELIMINAR"+usuario);
        X.eliminarUsuario(usuario);
        actualizarTabla();
        limpiar();

    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        btnadd.setEnabled(true);
        btndelete.setEnabled(false);
        btnupdate.setEnabled(false);
        limpiar();
    }//GEN-LAST:event_btnnewActionPerformed

    private void txtbusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaKeyPressed

    }//GEN-LAST:event_txtbusquedaKeyPressed

    private void txtbusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaKeyReleased
        String textoBusqueda = txtbusqueda.getText().toLowerCase();
        System.out.println(""+textoBusqueda);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + textoBusqueda));
        tabla.setRowSorter(sorter);

        int rowCount = sorter.getViewRowCount();
    }//GEN-LAST:event_txtbusquedaKeyReleased

    private void txtbusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaKeyTyped
        // TODO add your handling code here:}
    }//GEN-LAST:event_txtbusquedaKeyTyped

    private void txtuserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyReleased
               String nombreuser= txtuser.getText();

        if(nombreuser.equals("")){
                      juser.setText("");

      }else{
        if(X.usuarioverificar(nombreuser)==true){
            juser.setText("NOMBRE USUARIO YA EXISTE");
            juser.setForeground(Color.RED);
            validacion=2;

        }else{
            juser.setText("NOMBRE USUARIO VALIDO");
            Color verdeOscuro = new Color(0, 128, 0);
            juser.setForeground(verdeOscuro);
            validacion=1;

        }  
      }         // TODO add your handling code here:
    }//GEN-LAST:event_txtuserKeyReleased

    private void txtdniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdniKeyReleased
       String dni= txtdni.getText();

        if(dni.equals("")){
                      jdni.setText("");

      }else{
        if(X.dniverificar(dni)==true){
            jdni.setText("DNI USUARIO YA EXISTE");
            jdni.setForeground(Color.RED);
            validacion=2;

        }else{
            jdni.setText("DNI USUARIO VALIDO");
            Color verdeOscuro = new Color(0, 128, 0);
            jdni.setForeground(verdeOscuro);
            validacion=1;

        }  
      }         // TODO add your handling code here:
    }//GEN-LAST:event_txtdniKeyReleased

    private void txtcorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorreoKeyReleased
                    String correo= txtcorreo.getText();

        if(correo.equals("")){
                      jcorreo.setText("");

      }else{
        if(X.correoverificar(correo)==true){
            jcorreo.setText("CORREO YA EXISTE");
            jcorreo.setForeground(Color.RED);
            validacion=2;

        }else{
            jcorreo.setText("CORREO USUARIO VALIDO");
            Color verdeOscuro = new Color(0, 128, 0);
            jcorreo.setForeground(verdeOscuro);
            validacion=1;

        }  
      }        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoKeyReleased

    private void txtcorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcorreoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoFocusLost

    private void txtnumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumeroFocusLost
        validarNumeroEntero();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumeroFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
             X.exportarExcel(tabla);        // TODO add your handling code here:
         } catch (IOException ex) {
             Logger.getLogger(AdminTrabajador.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroKeyReleased
        // TODO add your handling code here:
        
                                   
         int X=txtnumero.getText().length();
        if(X==9){
            txtnumeroayuda.setText("NUMERO VALIDO");
            Color verdeOscuro = new Color(0, 128, 0);
            txtnumeroayuda.setForeground(verdeOscuro);

        }else{
            txtnumeroayuda.setForeground(Color.red);
            txtnumeroayuda.setText("NUMERO NO VALIDO");
            txtnumeroayuda.setForeground(Color.RED);

        }        // TODO add your handling code here:
        
                if(X>9){
             txtnumero.setText(txtnumero.getText().substring(0, 9));
            txtnumeroayuda.setText("NUMERO VALIDO");
            Color verdeOscuro = new Color(0, 128, 0);
            txtnumeroayuda.setForeground(verdeOscuro);

        }     
    }//GEN-LAST:event_txtnumeroKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cb_servicio;
    private javax.swing.JComboBox<String> cb_sexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jcorreo;
    private javax.swing.JLabel jdni;
    private javax.swing.JLabel juser;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtbusqueda;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcontra;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JLabel txtnumeroayuda;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
