/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatLightLaf;
import dao.daoServicios;
import dao.daoTrabajador2;
import dao.daoUsuario;
import java.awt.Color;
import java.io.IOException;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JRadioButton;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.event.RowSorterEvent;
import javax.swing.event.RowSorterListener;
import modelo.Servicios;
import modelo.Trabajador2;
import modelo.Usuario;
import modelo.Usuario2;
import modelo.empleador;

/**
 *
 * @author Adria
 */
public class adminUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form adminUsuarios
     */
     DefaultTableModel model = new DefaultTableModel();
          DefaultTableModel model1 = new DefaultTableModel();
          daoUsuario X=new daoUsuario();
     TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
    int validacion;

    public adminUsuarios() {
        FlatLightLaf.setup();
        initComponents();
        btnupdate.setEnabled(false);
        tabla.setModel(model);
        model.addColumn("IDEMPLEADO");
        model.addColumn("TIPO DE CUENTA");
        model.addColumn("CODIGO");
        model.addColumn("CONTRASEÑA");
        model.addColumn("DNI");
        model.addColumn("NOMBRE");
        model.addColumn("TELEFONO");
        model.addColumn("EMAIL");
        juser.setText("");     
        jdni.setText("");
        jcorreo.setText("");

        txtnumeroayuda.setText("");
        X.Iniciartabla(model);
        txtid.setText(X.generarCodigoEspecialidad()); 
        actualizarTabla();
        btndelete.setEnabled(false);
        btnupdate.setEnabled(false);
        cbtipo.addItem("Todo");
        cbtipo.addItem("Persona Natural");
        cbtipo.addItem("Persona Juridica");
   
        cbtipocuenta.addItem("Persona Natural");
        cbtipocuenta.addItem("Persona Juridica");

    }
  
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtdni = new javax.swing.JTextField();
        txtcontra = new javax.swing.JTextField();
        txtnum = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnnew = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtbusqueda = new javax.swing.JTextField();
        juser = new javax.swing.JLabel();
        txtnumeroayuda = new javax.swing.JLabel();
        cbtipocuenta = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jdni = new javax.swing.JLabel();
        jcorreo = new javax.swing.JLabel();
        cbtipo = new javax.swing.JComboBox<>();
        txtcorreo = new javax.swing.JTextField();
        txtuser = new javax.swing.JTextField();
        EXCEL = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("CRUD EMPLEADOR");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 40));

        jLabel2.setText("Codigo Usuario");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel3.setText("NOMBRE");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel4.setText("DNI/RUC");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jLabel6.setText("CONTRASEÑA");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        jLabel7.setText("NUMERO");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, -1, -1));

        jLabel8.setText("CORREO");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));
        add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 107, -1));

        txtdni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdniKeyReleased(evt);
            }
        });
        add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 107, -1));
        add(txtcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 107, -1));

        txtnum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnumFocusLost(evt);
            }
        });
        txtnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnumKeyReleased(evt);
            }
        });
        add(txtnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 150, -1));

        btnadd.setText("AÑADIR");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 99, -1));

        btndelete.setText("ELIMINAR");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 107, -1));

        btnupdate.setText("ACTUALIZAR");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        btnnew.setText("NUEVO");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });
        add(btnnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 107, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tablaMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 890, 320));

        jLabel11.setText("BUSQUEDA:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        txtbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbusquedaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbusquedaKeyTyped(evt);
            }
        });
        add(txtbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 300, 30));

        juser.setText("codigo");
        add(juser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 107, -1));

        txtnumeroayuda.setText("NUMERO");
        add(txtnumeroayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 107, -1));

        add(cbtipocuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        jLabel9.setText("TIPO DE CUENTA");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, 20));

        jLabel10.setText("ID Empleador");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtid.setEditable(false);
        add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 100, -1));

        jdni.setText("dni");
        add(jdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 50, -1));

        jcorreo.setText("correo");
        add(jcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        cbtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtipoActionPerformed(evt);
            }
        });
        add(cbtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, -1, -1));

        txtcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcorreoKeyReleased(evt);
            }
        });
        add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 110, -1));

        txtuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtuserKeyReleased(evt);
            }
        });
        add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 110, -1));

        EXCEL.setText("EXCEL");
        EXCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXCELActionPerformed(evt);
            }
        });
        add(EXCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtbusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaKeyPressed

    }//GEN-LAST:event_txtbusquedaKeyPressed

    private void txtbusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaKeyReleased
        String textoBusqueda = txtbusqueda.getText().toLowerCase();
        System.out.println(""+textoBusqueda);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + textoBusqueda));
        tabla.setRowSorter(sorter);

        int rowCount = sorter.getViewRowCount();

    }//GEN-LAST:event_txtbusquedaKeyReleased

    private void txtbusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaKeyTyped
        // TODO add your handling code here:}

    }//GEN-LAST:event_txtbusquedaKeyTyped
   public boolean validarletra(String letra){
    return letra.matches("^[a-zA-Z\\s]+$");
    }
   
    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String nombre,dni,contra,usuario,numero,correo,tipocuenta;
        nombre=txtnombre.getText();
        usuario=txtuser.getText();
        dni=txtdni.getText();
        contra=txtcontra.getText();
        correo=txtcorreo.getText();
        tipocuenta=cbtipocuenta.getSelectedItem().toString();
        String tipoc="";
        numero=txtnum.getText();
        String numeroString = "51" +numero; 
                                              Usuario u=new Usuario();
                                              empleador e=new empleador();
  
                               if (!nombre.isEmpty() && !dni.isEmpty() && !usuario.isEmpty() &&
                        !contra.isEmpty() && !correo.isEmpty() && 
                        !numero.isEmpty()) {
                        
                                   if(validacion==1){
                                   if(numeroString.length() == 11){
                                       if(esNumeroEntero(numero)){

                                           if(tipocuenta.equals("Persona Juridica")){
                                            e.setFk_codigoTipoeEmpl("20");
                                              e.setNombEmpl(nombre);
                                           }else{
                                            if(validarletra(nombre)==true ){
                                             e.setFk_codigoTipoeEmpl("10");
                                             e.setNombEmpl(nombre);

                                            }else{
                                                System.out.println("INGRESAR SOLO LETRAS PARA EL NOMBRE"); 
                                            }  
                                           }                                               
                                                u.setCodiUsua(usuario);
                                                u.setPassUsua(contra);
                                                u.setTipoUsua("cliente");
                                                e.setCodiEmpl(X.generarCodigoEspecialidad() );
                                                e.setDniRucEmpl(dni);
                                                e.setEmailEmpl(correo);
                                                e.setFk_codiUsa(usuario);
                                                e.setTeleEmpl(numeroString);

                                                X.crearUsuario(u, e);
                                      
                                                                              limpiar();

                                        actualizarTabla();                                     

                                       }else{
                                      JOptionPane.showMessageDialog(null, "NUMERO DEBE SER NUMERS");
  
                                       }
                                   }else{
                                       JOptionPane.showMessageDialog(null, "NUMERO DEBE SER NUEVO DIGITOS");

                                   }
     

                               }   else{
                                JOptionPane.showMessageDialog(null, "USUARIO YA EXISTENTE");
 
                               }
                            
                    }else{
                   JOptionPane.showMessageDialog(null,"Todos los campos deben estar completos");

                    } 
        

    }//GEN-LAST:event_btnaddActionPerformed
    private void limpiar(){
        txtnombre.setText("");
        txtdni.setText("");
        txtcorreo.setText("");
        txtnum.setText("");
        txtnumeroayuda.setText("");
        txtcontra.setText("");
        txtuser.setText("");
        juser.setText("");     
        jdni.setText("");
        jcorreo.setText("");
        txtid.setText(X.generarCodigoEspecialidad()); 

    }
    private boolean esNumeroEntero(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
        private void validarNumeroEntero() {
        String cadena = txtnum.getText();
        if (esNumeroEntero(cadena)) {
        } else {
       JOptionPane.showMessageDialog(null, "SOLO SE DEBE INGRESAR NUMEROS");
       txtnum.setText("");
        }
    }

public void actualizarTabla() {
    // Limpiar el modelo
    model.setRowCount(0);

    // Volver a cargar los datos en el modelo
    X.Iniciartabla(model);

    // Notificar al TableRowSorter sobre los cambios en el modelo
    sorter.modelStructureChanged();

    // Obtener el número de filas en la vista del TableRowSorter
    int rowCount = sorter.getViewRowCount();

    // Imprimir información sobre el rango de filas en la vista
    System.out.println("Rango de filas actual: 0 - " + (rowCount - 1));
    System.out.println("Número total de filas en el modelo: " + model.getRowCount());
    
    // Restablecer el modelo en la tabla (puede que no sea necesario en algunos casos)
    tabla.setModel(model);
}


    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed

    int filaSeleccionada = tabla.getSelectedRow();
    int filaSeleccionadaModelo = sorter.convertRowIndexToModel(filaSeleccionada);

        System.out.println("fila"+filaSeleccionadaModelo);
             String  usuario = (txtuser.getText());
             System.out.println("ID ELIMINAR"+usuario);
             X.eliminarUsuario(usuario);
            actualizarTabla();
            limpiar();



    }//GEN-LAST:event_btndeleteActionPerformed

    private void txtdniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdniKeyReleased
       String dni= txtdni.getText();

        if(dni.equals("")){
                      jdni.setText("");

      }else{
        if(X.dniverificar(dni)==true){
            jdni.setText("DNI USUARIO YA EXISTE");
            jdni.setForeground(Color.RED);
            validacion=2;

        }else{
            jdni.setText("DNI USUARIO VALIDO");
            Color verdeOscuro = new Color(0, 128, 0);
            jdni.setForeground(verdeOscuro);
            validacion=1;

        }  
      }       // TODO add your handling code here:
    }//GEN-LAST:event_txtdniKeyReleased

    private void txtnumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumFocusGained

    private void txtnumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumKeyReleased
         int X=txtnum.getText().length();
        if(X==9){
            txtnumeroayuda.setText("NUMERO VALIDO");
            Color verdeOscuro = new Color(0, 128, 0);
            txtnumeroayuda.setForeground(verdeOscuro);

        }else{
            txtnumeroayuda.setForeground(Color.red);
            txtnumeroayuda.setText("NUMERO NO VALIDO");
            txtnumeroayuda.setForeground(Color.RED);

        }        // TODO add your handling code here:
        
                if(X>9){
             txtnum.setText(txtnum.getText().substring(0, 9));
            txtnumeroayuda.setText("NUMERO VALIDO");
            Color verdeOscuro = new Color(0, 128, 0);
            txtnumeroayuda.setForeground(verdeOscuro);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumKeyReleased

    private void txtnumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumFocusLost
        // TODO add your handling code here:             
        validarNumeroEntero();

    }//GEN-LAST:event_txtnumFocusLost

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        btnadd.setEnabled(false);
        btndelete.setEnabled(true);
        btnupdate.setEnabled(true);
        int filaSeleccionadaModelo = tabla.getSelectedRow();
     int filaSeleccionada = sorter.convertRowIndexToModel(filaSeleccionadaModelo);
        System.out.println("FILA"+filaSeleccionada);
        String id = (model.getValueAt(filaSeleccionada, 0).toString());
        String tipocuenta = (model.getValueAt(filaSeleccionada, 1).toString());
        String codigo = (model.getValueAt(filaSeleccionada, 2).toString());
        String contra = (model.getValueAt(filaSeleccionada, 3).toString());
        String dni = (model.getValueAt(filaSeleccionada, 4).toString());
        String nombre = (model.getValueAt(filaSeleccionada, 5).toString());
        String telefono = (model.getValueAt(filaSeleccionada, 6).toString());
        String mail = (model.getValueAt(filaSeleccionada, 7).toString());
        
        
        txtid.setText(id);
        txtuser.setText(""+codigo);
        txtnombre.setText(""+nombre);
        txtdni.setText(""+dni);
        txtcorreo.setText(""+mail);
        txtnum.setText(""+telefono);
        txtcontra.setText(""+contra );
        if(tipocuenta.equals("Persona Natural"))        {
            cbtipocuenta.setSelectedItem("Persona Natural");
        }else{
            cbtipocuenta.setSelectedItem("Persona Juridica");

        }
                
        

    }//GEN-LAST:event_tablaMouseClicked

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        btnadd.setEnabled(true);
        btndelete.setEnabled(false);
        btnupdate.setEnabled(false);  
        limpiar();
    }//GEN-LAST:event_btnnewActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
 
       String id,usuario,contra,correo,numero,nombre,dni,tipo;
        nombre=txtnombre.getText();
        usuario=txtuser.getText();
        contra=txtcontra.getText();
        correo=txtcorreo.getText();
        numero=txtnum.getText();
        id=txtid.getText();
        dni=txtdni.getText();
                String numeroString = "51" +numero; 

String tipocuenta = (String) cbtipocuenta.getSelectedItem();

        tipo="";
                                      if(tipocuenta.equals("Persona Juridica")){
                                            tipo="20";
                                           }else{
                                            if(validarletra(nombre)==true ){
                                            tipo="10";  }
            
                                     }
                                      
          X.actualizarusuario(id, dni, nombre, numeroString, correo, tipo, usuario, contra);
        actualizarTabla();
        limpiar(); 
    }//GEN-LAST:event_btnupdateActionPerformed
                                      
    private void cbtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtipoActionPerformed
        // TODO add your handling code here:
            String textoBusqueda = "";
         String opcionSeleccionada = (String) cbtipo.getSelectedItem();
                switch (opcionSeleccionada) {
                    case "Todo":
                              textoBusqueda = "";
                        break;

                    case "Persona Natural":
                        // Acciones para la Opción 2
                        textoBusqueda = "Persona Natural";
                        break;

                    case "Persona Juridica":
                        textoBusqueda = "Persona Juridica";
                        break;

                }
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + textoBusqueda));
        tabla.setRowSorter(sorter);

        int rowCount = sorter.getViewRowCount();  
 
    }//GEN-LAST:event_cbtipoActionPerformed

    private void txtcorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorreoKeyReleased
        // TODO add your handling code here:
                    String correo= txtcorreo.getText();

        if(correo.equals("")){
                      jcorreo.setText("");

      }else{
        if(X.correoverificar(correo)==true){
            jcorreo.setText("CORREO YA EXISTE");
            jcorreo.setForeground(Color.RED);
            validacion=2;

        }else{
            jcorreo.setText("CORREO USUARIO VALIDO");
            Color verdeOscuro = new Color(0, 128, 0);
            jcorreo.setForeground(verdeOscuro);
            validacion=1;

        }  
      }
    }//GEN-LAST:event_txtcorreoKeyReleased

    private void txtuserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyReleased
        // TODO add your handling code here:
               String nombreuser= txtuser.getText();

        if(nombreuser.equals("")){
                      juser.setText("");

      }else{
        if(X.usuarioverificar(nombreuser)==true){
            juser.setText("NOMBRE USUARIO YA EXISTE");
            juser.setForeground(Color.RED);
            validacion=2;

        }else{
            juser.setText("NOMBRE USUARIO VALIDO");
            Color verdeOscuro = new Color(0, 128, 0);
            juser.setForeground(verdeOscuro);
            validacion=1;

        }  
      } 
    }//GEN-LAST:event_txtuserKeyReleased

    private void EXCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXCELActionPerformed
         try {
             // TODO add your handling code here:
             X.exportarExcel(tabla);
         } catch (IOException ex) {
             Logger.getLogger(adminUsuarios.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
    }//GEN-LAST:event_EXCELActionPerformed

    private void tablaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXCEL;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cbtipo;
    private javax.swing.JComboBox<String> cbtipocuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jcorreo;
    private javax.swing.JLabel jdni;
    private javax.swing.JLabel juser;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtbusqueda;
    private javax.swing.JTextField txtcontra;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnum;
    private javax.swing.JLabel txtnumeroayuda;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
