package vista;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.text.SimpleDateFormat;
import dao.ContratoDao;
import modelo.Trabajador;

/**
 *
 * @author Nelson
 */
public class clienteContrato extends javax.swing.JPanel {
    ContratoDao objCont = new ContratoDao();
    /**
     * Creates new form clienteContrato
     */
    public clienteContrato(Trabajador trab) {
        FlatLightLaf.setup();
        initComponents();
    }

    public void generar(){
        // Obtener la fecha actual
        txtCodContrat.setText(TOOL_TIP_TEXT_KEY);
        SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
        String fechaFormateada = formato.format(new java.sql.Date(new java.util.Date().getTime()));
        txtFecNego.setText(fechaFormateada);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodContrat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFecNego = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFecNego1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFecNego2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensaje = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txtCaracteres = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txtEstado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCodTrab = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTrabNombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Contratos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 400, 40));

        jLabel2.setText("Codigo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        txtCodContrat.setEnabled(false);
        jPanel1.add(txtCodContrat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 100, -1));

        jLabel3.setText("Fecha");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 40, 20));

        txtFecNego.setEnabled(false);
        jPanel1.add(txtFecNego, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 120, -1));

        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("\"dd-MM-yyyy\"");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 90, 20));

        txtFecNego1.setEnabled(false);
        jPanel1.add(txtFecNego1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 120, -1));

        jLabel5.setText("Fecha Final Contrato");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 120, 20));

        txtFecNego2.setEnabled(false);
        jPanel1.add(txtFecNego2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 120, -1));

        jLabel6.setText("Fecha Inicio Contrato");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 130, 20));

        mensaje.setColumns(20);
        mensaje.setLineWrap(true);
        mensaje.setRows(5);
        mensaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mensajeKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(mensaje);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 870, 100));

        jLabel7.setText("Descripcion de contrato: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        txtCaracteres.setText("0/255");
        jPanel1.add(txtCaracteres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 70, -1));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 10, 20));

        txtEstado.setEnabled(false);
        jPanel1.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 120, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Estado");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 50, 20));

        txtCodTrab.setText("codigo");
        jPanel1.add(txtCodTrab, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 60, 20));

        jLabel10.setText("cod: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 30, 20));

        txtTrabNombre.setEnabled(false);
        jPanel1.add(txtTrabNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 150, -1));

        jLabel11.setText("Para :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mensajeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mensajeKeyReleased
        int tamaño = mensaje.getText().length();
        int maximo = 255;

        if (tamaño == maximo) {
            txtCaracteres.setText(tamaño + "/" + 255);
            txtCaracteres.setForeground(new Color(0, 128, 0)); // Verde oscuro
        } else if (tamaño > maximo) {
            mensaje.setText(mensaje.getText().substring(0, maximo)); // Truncar al tamaño máximo
            txtCaracteres.setText(maximo + "/" + 255);
            txtCaracteres.setForeground(Color.RED); // Verde oscuro
        } else {
            txtCaracteres.setText(tamaño + "/" + 255);
            txtCaracteres.setForeground(new Color(0, 128, 0)); // Rojo
        }
    }//GEN-LAST:event_mensajeKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextArea mensaje;
    private javax.swing.JLabel txtCaracteres;
    private javax.swing.JTextField txtCodContrat;
    private javax.swing.JLabel txtCodTrab;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFecNego;
    private javax.swing.JTextField txtFecNego1;
    private javax.swing.JTextField txtFecNego2;
    private javax.swing.JTextField txtTrabNombre;
    // End of variables declaration//GEN-END:variables
}
