package vista;

import com.formdev.flatlaf.FlatLightLaf;
import dao.daoEspecialidad;
import dao.daoNegociacion;
import java.awt.Color;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import modelo.Especialidad;
import modelo.Negociacion;
import modelo.Trabajador;
import modelo.Usuario;

/**
 *
 * @author Nelson
 */
public class clienteNegociacion extends javax.swing.JPanel {
    daoNegociacion objNeg = new daoNegociacion();
    daoEspecialidad objEsp = new daoEspecialidad();
    Trabajador trab;
    Usuario user;
    Especialidad esp;
    /**
     * Creates new form clienteNegociacion
     */
    public clienteNegociacion(Trabajador trab, Usuario user) {
        FlatLightLaf.setup();
        initComponents();
        
        this.trab = trab;
        this.user = user;
        esp = objEsp.obtener(trab.getCodiEspe());
        
        generar();
    }

    public void generar(){
        txtNuevoMonto.setText(String.valueOf(esp.getPrecBaseEspe()));
        txtCodNego.setText(objNeg.obtenerNuevoCodigoNegociacion());
        
        // Obtener la fecha actual
        SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
        String fechaFormateada = formato.format(new java.sql.Date(new java.util.Date().getTime()));
        txtFecNego.setText(fechaFormateada);
        
        //String estado = "En progreso";
        txtTrabNombre.setText(trab.getNombTrab()+" "+trab.getApelTrab());
        txtCodTrab.setText(trab.getCodiTrab());
        
        txtEspNombre.setText(esp.getNombEspe());
        txtEspMonto.setText(String.valueOf(esp.getPrecBaseEspe()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodNego = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFecNego = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTrabNombre = new javax.swing.JTextField();
        txtCodTrab = new javax.swing.JLabel();
        txtEspMonto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensaje = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtEspNombre = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCaracteres = new javax.swing.JLabel();
        cstmButon2 = new guiRecursos.cstmButon();
        cstmButon3 = new guiRecursos.cstmButon();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtNuevoMonto = new javax.swing.JTextField();
        cstmButon4 = new guiRecursos.cstmButon();

        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Negocicacion");
        Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 400, 50));

        jLabel2.setText("Codigo");
        Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        txtCodNego.setEnabled(false);
        Panel.add(txtCodNego, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 100, -1));

        jLabel3.setText("Fecha");
        Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 40, 20));

        txtFecNego.setEnabled(false);
        Panel.add(txtFecNego, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 100, -1));

        jLabel4.setText("Para :");
        Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 20));

        txtTrabNombre.setEnabled(false);
        Panel.add(txtTrabNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 190, -1));

        txtCodTrab.setText("codigo");
        Panel.add(txtCodTrab, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 60, 20));

        txtEspMonto.setText("monto");
        Panel.add(txtEspMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 110, 20));

        mensaje.setColumns(20);
        mensaje.setLineWrap(true);
        mensaje.setRows(5);
        mensaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mensajeKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(mensaje);

        Panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 870, 100));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Panel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 10, 20));

        jLabel7.setText("cod: ");
        Panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 30, 20));

        txtEspNombre.setText("codigo");
        Panel.add(txtEspNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 190, 20));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Panel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 10, 20));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Panel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 10, 20));

        jLabel8.setText("Especialidad:");
        Panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 80, 20));

        jLabel9.setText("Monto a negociar");
        Panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 120, 20));

        jLabel5.setText("Mensaje a enviar : ");
        Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        txtCaracteres.setText("0/255");
        Panel.add(txtCaracteres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 70, -1));

        cstmButon2.setForeground(new java.awt.Color(255, 255, 255));
        cstmButon2.setText("Obtener de monto base");
        cstmButon2.setColor(new java.awt.Color(144, 148, 151));
        cstmButon2.setColorClick(new java.awt.Color(215, 219, 221));
        cstmButon2.setColorOver(new java.awt.Color(166, 172, 175));
        cstmButon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cstmButon2ActionPerformed(evt);
            }
        });
        Panel.add(cstmButon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 180, -1));

        cstmButon3.setForeground(new java.awt.Color(255, 255, 255));
        cstmButon3.setText("Volver a Ofertas");
        cstmButon3.setColor(new java.awt.Color(52, 73, 94));
        cstmButon3.setColorClick(new java.awt.Color(170, 183, 184));
        cstmButon3.setColorOver(new java.awt.Color(93, 109, 126));
        Panel.add(cstmButon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 130, -1));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Panel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 10, 20));

        jLabel10.setText("Monto base:");
        Panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 80, 20));
        Panel.add(txtNuevoMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 110, -1));

        cstmButon4.setForeground(new java.awt.Color(255, 255, 255));
        cstmButon4.setText("Enviar");
        cstmButon4.setColor(new java.awt.Color(52, 73, 94));
        cstmButon4.setColorClick(new java.awt.Color(170, 183, 184));
        cstmButon4.setColorOver(new java.awt.Color(93, 109, 126));
        cstmButon4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cstmButon4ActionPerformed(evt);
            }
        });
        Panel.add(cstmButon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mensajeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mensajeKeyReleased
        int tamaño = mensaje.getText().length();
        int maximo = 255;

        if (tamaño == maximo) {
            txtCaracteres.setText(tamaño + "/" + 255);
            txtCaracteres.setForeground(new Color(0, 128, 0)); // Verde oscuro
        } else if (tamaño > maximo) {
            mensaje.setText(mensaje.getText().substring(0, maximo)); // Truncar al tamaño máximo
            txtCaracteres.setText(maximo + "/" + 255);
            txtCaracteres.setForeground(Color.RED); // Verde oscuro
        } else {
            txtCaracteres.setText(tamaño + "/" + 255);
            txtCaracteres.setForeground(new Color(0, 128, 0)); // Rojo
        }
    }//GEN-LAST:event_mensajeKeyReleased

    private void cstmButon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cstmButon2ActionPerformed
        txtNuevoMonto.setText(String.valueOf(esp.getPrecBaseEspe()));
    }//GEN-LAST:event_cstmButon2ActionPerformed

    private void cstmButon4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cstmButon4ActionPerformed
        if (validateNumber(txtNuevoMonto.getText())) {
            int opcion = JOptionPane.showConfirmDialog(null, "¿Esta seguro de enviar el mensaje?", "Decide", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                System.out.println("Sí");
                Negociacion neg = new Negociacion();
                neg.setCodiNego(objNeg.obtenerNuevoCodigoNegociacion());
                neg.setFechNego(Date.valueOf(LocalDate.now()));
                neg.setEstaNego("En Progreso");
                neg.setMontNego(esp.getPrecBaseEspe());
                neg.setDescNego(mensaje.getText());
                neg.setCodiTrab(trab.getCodiTrab());
                //Codigo de Empleador, no hay en este caso
                neg.setCodiCli(user.getCodiUsua());
                
                mostrardatos(neg);
                objNeg.crear(neg);
            } else {
                System.out.println("No");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese un monto nuevo válido", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_cstmButon4ActionPerformed

    public static boolean validateNumber(String input) {
        // Utilizar una expresión regular para verificar si la cadena contiene solo números o números con decimales
        return input.matches("-?\\d+(\\.\\d+)?");
    }
    
    public void mostrardatos(Negociacion neg){
        // Mostrar los datos en consola
        System.out.println("Código de Negociación: " + neg.getCodiNego());
        System.out.println("Fecha de Negociación: " + neg.getFechNego());
        System.out.println("Estado de Negociación: " + neg.getEstaNego());
        System.out.println("Monto de Negociación: " + neg.getMontNego());
        System.out.println("Descripción de Negociación: " + neg.getDescNego());
        System.out.println("Código de Trabajador: " + neg.getCodiTrab());
        System.out.println("Código de Empleado: " + neg.getCodiCli());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private guiRecursos.cstmButon cstmButon2;
    private guiRecursos.cstmButon cstmButon3;
    private guiRecursos.cstmButon cstmButon4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextArea mensaje;
    private javax.swing.JLabel txtCaracteres;
    private javax.swing.JTextField txtCodNego;
    private javax.swing.JLabel txtCodTrab;
    private javax.swing.JLabel txtEspMonto;
    private javax.swing.JLabel txtEspNombre;
    private javax.swing.JTextField txtFecNego;
    private javax.swing.JTextField txtNuevoMonto;
    private javax.swing.JTextField txtTrabNombre;
    // End of variables declaration//GEN-END:variables
}
