package vista;

import com.formdev.flatlaf.FlatLightLaf;
import dao.EmpleadorDao;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import modelo.Usuario;

/**
 *
 * @author Nelson
 */
public class clienteHistorial extends javax.swing.JPanel{
    EmpleadorDao daoEmp = new EmpleadorDao();
    
    public clienteHistorial(Usuario user) {
        FlatLightLaf.setup();
        initComponents();
        String codEmp = daoEmp.obtenerEmpleadorPorIDUsuario(user.getCodiUsua()).getCodiEmpl();
        
    }

    public void MostrarPanel(JPanel panel){
        panel.setSize(this.getWidth(),this.getHeight());
        panel.setLocation(0,0);
        this.removeAll();
        this.add(panel, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        scroll = new guiRecursos.GuiJScrollPane();
        panelContratos = new javax.swing.JPanel();

        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Historial");
        Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 400, 40));

        jLabel2.setText("Aquí, el cliente puede ver un historial de todas las contrataciones pasadas, asi como las negociaciones");
        Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 840, 20));

        javax.swing.GroupLayout panelContratosLayout = new javax.swing.GroupLayout(panelContratos);
        panelContratos.setLayout(panelContratosLayout);
        panelContratosLayout.setHorizontalGroup(
            panelContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 908, Short.MAX_VALUE)
        );
        panelContratosLayout.setVerticalGroup(
            panelContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        scroll.setViewportView(panelContratos);

        Panel.add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 910, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelContratos;
    private guiRecursos.GuiJScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
