/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import dao.EmpleadorDao;
import dao.daoEmpleador;
import dao.daoTrabajador;
import java.awt.Color;
import java.awt.Image;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import modelo.Usuario;
import modelo.empleador;
import util.MySQLConexionOriginal;

/**
 *
 * @author Adria
 */
public class ConfiguracionCliente extends javax.swing.JFrame {

    /**
     * Creates new form ConfiguracionCliente
     */
        private empleador empleador;
    int validacion=1;
    public ConfiguracionCliente(empleador empleador) {
  
                initComponents();
        this.empleador = empleador;
        System.out.println("empleadorcodigo: "+this.empleador.getFk_codiUsua()+",nombre:"+this.empleador.getNombEmpl()+",tipo:");
        String codigo=this.empleador.getCodiEmpl();
        String nombre=this.empleador.getNombEmpl();
        String usuario=this.empleador.getFk_codiUsua();//ESTO SE DEBE CA
        String telefono=this.empleador.getTeleEmpl();
        String correo=this.empleador.getEmailEmpl();
        txtnom.setText(nombre);
        txtuser.setText(usuario);
        txtcorreo.setText(correo);
        txtelefono.setText(telefono);
        juser.setText("");
        lnumero.setText("");
        lcorreo.setText("");
String textoOriginal = txtelefono.getText();

if (textoOriginal.length() >= 2) {
    String textoSinPrimerosDos = textoOriginal.substring(2);
    txtelefono.setText(textoSinPrimerosDos);
} else {
    System.out.println("El texto es demasiado corto para quitar los primeros dos caracteres.");
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtuser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtelefono = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        juser = new javax.swing.JLabel();
        lnumero = new javax.swing.JLabel();
        lcorreo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("GUARDAR CAMBIOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("NOMBRE");

        jButton2.setText("ELIMINAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtuserKeyReleased(evt);
            }
        });

        jLabel2.setText("USUARIO");

        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });

        jButton3.setText("CAMBIAR CONTRASEÑA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtelefonoFocusLost(evt);
            }
        });
        txtelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtelefonoKeyReleased(evt);
            }
        });

        txtcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcorreoKeyReleased(evt);
            }
        });

        jLabel3.setText("TELEFONO");

        jLabel4.setText("CORREO");

        juser.setText("USUARIO");

        lnumero.setText("TELEFONO");

        lcorreo.setText("CORREO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(152, 152, 152)
                        .addComponent(txtuser))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnom)
                            .addComponent(juser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtcorreo)
                            .addComponent(txtelefono)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lcorreo)
                                    .addComponent(lnumero))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(juser)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lnumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lcorreo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(28, 28, 28)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String nombre = txtnom.getText();
        String usuario = empleador.getFk_codiUsua();
        String telefono = txtelefono.getText();
        String correo = txtcorreo.getText();
        String nuevouser=txtuser.getText();

        String numeroString = "51" +telefono;

        if (!nombre.isEmpty()  && !nuevouser.isEmpty() &&
            !telefono.isEmpty() && !correo.isEmpty() )
        {
            if(numeroString.length() == 11){
                if(validacion==1){
                    if(validarletra(nombre)==true ){
                        int respuesta = JOptionPane.showConfirmDialog(null, "¿Quieres Actualizar?", "Confirmación", JOptionPane.YES_NO_OPTION);
                        if (respuesta == JOptionPane.YES_OPTION) {
                            System.out.println("El usuario seleccionó Sí.");                                                 EmpleadorDao Ed=new EmpleadorDao();

                            empleador z=new empleador();
                            z.setEmailEmpl(correo);
                            z.setFk_codiUsua(usuario);
                            z.setNombEmpl(nombre);
                            z.setTeleEmpl(telefono);
                            Ed.ACTUALIZARMPLEADO(nombre, numeroString, correo, usuario,nuevouser);
                            this.dispose();
                            Usuario l=new Usuario();
                            l.setCodiUsua(nuevouser);
                            
                           new frmMenuCliente(l).setVisible(true);
                        }

                    }else{
                        JOptionPane.showMessageDialog(null,"INGRESAR SOLO LETRAS PARA EL NOMBRE");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "DATOS YA EXISTEN ");

                }

            }else{
                JOptionPane.showMessageDialog(null, "NUMERO DEBE SER NUEVO DIGITOS");
            }

        }else{
            JOptionPane.showMessageDialog(null,"Todos los campos deben estar completos");

        }

    }//GEN-LAST:event_jButton1ActionPerformed
    private boolean esNumeroEntero(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
        private void validarNumeroEntero() {
        String cadena = txtelefono.getText();
        if (esNumeroEntero(cadena)) {
        } else {
       JOptionPane.showMessageDialog(null, "SOLO SE DEBE INGRESAR NUMEROS");
       txtelefono.setText("");
        }
    }    public boolean usuarioverificar(String usuario){
         Connection con = MySQLConexionOriginal.getConexion();

        try {
          String sql="SELECT codiUsua FROM usuario Where codiUsua=?";
          PreparedStatement ps=con.prepareStatement(sql);
          ps.setString(1, usuario);
          ResultSet rs=ps.executeQuery();
          boolean validar=rs.next();
          return validar;
        } catch (Exception e) {
            return false;
        }
    }
    public boolean validarletra(String letra){
    return letra.matches("^[a-zA-Z\\s]+$");
}
    public void imageIconCambiar(URL resource, JLabel iconoMod, int tamaño) {
        ImageIcon iconLogo = new ImageIcon(resource);
        Image image = iconLogo.getImage();
        Image imgRescalado = image.getScaledInstance(tamaño, tamaño, java.awt.Image.SCALE_SMOOTH);
        iconLogo = new ImageIcon(imgRescalado);
        iconoMod.setIcon(iconLogo);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int respuesta = JOptionPane.showConfirmDialog(null, "¿Quieres Eliminar?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            String usuario =empleador.getFk_codiUsua();
            EmpleadorDao J=new EmpleadorDao()
            ;
            J.eliminarUsuario(usuario);
            setVisible(false);
            frmMenuCliente menu=new frmMenuCliente(null);
            menu.setVisible(false);
            frmLogin login=new frmLogin();
            login.setVisible(true);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtuserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyReleased
        String nombreuser= txtuser.getText();
        if(nombreuser.equalsIgnoreCase(empleador.getNombEmpl())){
            juser.setText("");
        }else{
            if(nombreuser.equals("")){
                juser.setText("");

            }else{
                if(usuarioverificar(nombreuser)==true){
                    juser.setText("NOMBRE USUARIO YA EXISTE");
                    juser.setForeground(Color.RED);
                    validacion=2;

                }else{
                    juser.setText("NOMBRE USUARIO VALIDO");
                    Color verdeOscuro = new Color(0, 128, 0);
                    juser.setForeground(verdeOscuro);
                    validacion=1;
                }
            }
        }
        int X=txtuser.getText().length();
        if(X>11){
            txtuser.setText(txtuser.getText().substring(0, 9));

        }
    }//GEN-LAST:event_txtuserKeyReleased

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        frm_cambiarcontra X=new frm_cambiarcontra(empleador.getFk_codiUsua());
        X.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtelefonoFocusLost
        // TODO add your handling code here:
        validarNumeroEntero();
    }//GEN-LAST:event_txtelefonoFocusLost

    private void txtelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtelefonoKeyReleased
        // TODO add your handling code here:
        int X=txtelefono.getText().length();
        if(X==9){
            lnumero.setText("NUMERO VALIDO");
            Color verdeOscuro = new Color(0, 128, 0);
            lnumero.setForeground(verdeOscuro);

        }else{
            lnumero.setForeground(Color.red);
            lnumero.setText("NUMERO NO VALIDO");
            lnumero.setForeground(Color.RED);

        }        // TODO add your handling code here:

        if(X>9){
            txtelefono.setText(txtelefono.getText().substring(0, 9));
            lnumero.setText("NUMERO VALIDO");
            Color verdeOscuro = new Color(0, 128, 0);
            lnumero.setForeground(verdeOscuro);

        }
    }//GEN-LAST:event_txtelefonoKeyReleased

    private void txtcorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorreoKeyReleased
        // TODO add your handling code here:
        String correo= txtcorreo.getText();
        EmpleadorDao X=new EmpleadorDao();

        if(correo.equalsIgnoreCase(empleador.getEmailEmpl())){
            lcorreo.setText("");

        }else{
            if(correo.equals("")){
                lcorreo.setText("");

            }else{
                if(X.correoverificar(correo)==true){
                    lcorreo.setText("CORREO  YA EXISTE");
                    lcorreo.setForeground(Color.RED);
                    validacion=2;

                }else{
                    lcorreo.setText("CORREO  VALIDO");
                    Color verdeOscuro = new Color(0, 128, 0);
                    lcorreo.setForeground(verdeOscuro);
                    validacion=1;

                }
            }
        }
    }//GEN-LAST:event_txtcorreoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfiguracionCliente(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel juser;
    private javax.swing.JLabel lcorreo;
    private javax.swing.JLabel lnumero;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtelefono;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
