package vista;


import com.formdev.flatlaf.FlatLightLaf;
import dao.daoUsuario;
import dao.daoUsuario2;
import java.awt.Color;
import java.awt.Image;
import java.net.URL;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import modelo.Usuario2;
import util.MySQLConexionOriginal;
import java.sql.*;
import javax.swing.ButtonGroup;
import modelo.Usuario;
import modelo.empleador;

/**
 *
 
 */
public class frmRegCliente extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistro
     */  Connection con = MySQLConexionOriginal.getConexion();
                  int campointento=0;
                  int campointento2=0;
                  int validacion=1;
      ButtonGroup tipocuenta = new ButtonGroup();
                   String tipo="";
    public frmRegCliente() {
        FlatLightLaf.setup();
        initComponents();
        txtnum.setText("");
        campoCon.setText("*****");
        campoCon2.setText("*****");
        imageIconCambiar(frmLogin.class.getResource("/images/con_ocultar_dark.png"), passicon, 20);
        imageIconCambiar(frmLogin.class.getResource("/images/con_ocultar_dark.png"), passicon1, 20);
                 funcionbotones();

    }
    public void funcionbotones(){

        tipocuenta.add(btnempresa);
        tipocuenta.add(btnpersona);
         btnpersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // Manejar la selección del JRadioButton "Trabajador"
                if (btnpersona.isSelected()) {
                    tipo="PERSONA";
                    lblNombre2.setText("DNI");
                    
                }
            }
        });
                  btnempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // Manejar la selección del JRadioButton "Trabajador"
                if (btnempresa.isSelected()) {
                    tipo="EMPRESA";
                  lblNombre2.setText("RUC");

                }
            }
        });
                      


    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtdni = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Separator1 = new javax.swing.JSeparator();
        lbltipo = new javax.swing.JLabel();
        Separator2 = new javax.swing.JSeparator();
        lblApellido1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        Separator3 = new javax.swing.JSeparator();
        lblApellido2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        Separator4 = new javax.swing.JSeparator();
        Separator6 = new javax.swing.JSeparator();
        Contraseña = new javax.swing.JLabel();
        errorCon = new javax.swing.JLabel();
        passicon = new javax.swing.JLabel();
        campoCon = new javax.swing.JPasswordField();
        Separator8 = new javax.swing.JSeparator();
        Contraseña1 = new javax.swing.JLabel();
        errorCon1 = new javax.swing.JLabel();
        passicon1 = new javax.swing.JLabel();
        juser = new javax.swing.JLabel();
        jred = new javax.swing.JLabel();
        Contraseña2 = new javax.swing.JLabel();
        campoCon2 = new javax.swing.JPasswordField();
        txtcodigo = new javax.swing.JTextField();
        txtnum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        btnpersona = new javax.swing.JRadioButton();
        btnempresa = new javax.swing.JRadioButton();
        lblNombre2 = new javax.swing.JLabel();
        guiBarraVentana1 = new guiRecursos.GuiBarraVentana();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 240, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("REGISTRO CLIENTE");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 290, -1));

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 180, -1));

        jLabel7.setForeground(new java.awt.Color(115, 128, 190));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Volver a Login");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 110, 20));
        jPanel1.add(Separator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 240, 10));

        lbltipo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbltipo.setText("TIPO");
        jPanel1.add(lbltipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 80, 20));
        jPanel1.add(Separator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 240, 10));

        lblApellido1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblApellido1.setText("Usuario");
        jPanel1.add(lblApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 80, 20));

        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyReleased(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 240, -1));
        jPanel1.add(Separator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 240, 10));

        lblApellido2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblApellido2.setText("Correo");
        jPanel1.add(lblApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 80, 20));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 240, -1));
        jPanel1.add(Separator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 240, 10));
        jPanel1.add(Separator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 180, 10));

        Contraseña.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Contraseña.setText("Contraseña");
        jPanel1.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 130, 20));
        jPanel1.add(errorCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 20, 20));

        passicon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passiconMouseClicked(evt);
            }
        });
        jPanel1.add(passicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 20, 20));

        campoCon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoConFocusGained(evt);
            }
        });
        campoCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoConKeyReleased(evt);
            }
        });
        jPanel1.add(campoCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 180, -1));
        jPanel1.add(Separator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 180, 10));

        Contraseña1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Contraseña1.setText("Numero");
        jPanel1.add(Contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 150, 20));
        jPanel1.add(errorCon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 20, 20));

        passicon1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passicon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passicon1MouseClicked(evt);
            }
        });
        jPanel1.add(passicon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 20, 20));
        jPanel1.add(juser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 190, 10));

        jred.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.add(jred, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 180, 20));

        Contraseña2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Contraseña2.setText("Repetir Contraseña");
        jPanel1.add(Contraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 150, 20));

        campoCon2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCon2FocusGained(evt);
            }
        });
        campoCon2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoCon2KeyReleased(evt);
            }
        });
        jPanel1.add(campoCon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 180, -1));

        txtcodigo.setEditable(false);
        txtcodigo.setText("+51");
        jPanel1.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 40, -1));

        txtnum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnumFocusLost(evt);
            }
        });
        txtnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnumKeyReleased(evt);
            }
        });
        jPanel1.add(txtnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 120, -1));

        jLabel1.setText("NUMER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 110, -1));

        lblNombre1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblNombre1.setText("Nombre");
        jPanel1.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, 20));
        jPanel1.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 240, -1));

        btnpersona.setText("PERSONA NORMAL");
        jPanel1.add(btnpersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        btnempresa.setText("EMPRESA");
        jPanel1.add(btnempresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        lblNombre2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblNombre2.setText("DNI");
        jPanel1.add(lblNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 80, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(guiBarraVentana1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(guiBarraVentana1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        frmLogin flog = new frmLogin();
        flog.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    boolean mostrarContrasena = false;
    private void passiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passiconMouseClicked
        mostrarContrasena = !mostrarContrasena;
        URL resource;
        if (mostrarContrasena) {
            campoCon.setEchoChar((char) 0); // Mostrar contraseña sin asteriscos
            resource = frmLogin.class.getResource("/images/con_mostrar_dark.png");
        } else {
            campoCon.setEchoChar('*'); // Mostrar contraseña con asteriscos
            resource = frmLogin.class.getResource("/images/con_ocultar_dark.png");
        }
        imageIconCambiar(resource, passicon, 20);
    }//GEN-LAST:event_passiconMouseClicked
    
    boolean mostrarRepContrasena = false;
    private void passicon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passicon1MouseClicked
        mostrarRepContrasena = !mostrarRepContrasena;
        URL resource;
        if (mostrarRepContrasena) {
            campoCon2.setEchoChar((char) 0); // Mostrar contraseña sin asteriscos
            resource = frmLogin.class.getResource("/images/con_mostrar_dark.png");
        } else {
            campoCon2.setEchoChar('*'); // Mostrar contraseña con asteriscos
            resource = frmLogin.class.getResource("/images/con_ocultar_dark.png");
        }
        imageIconCambiar(resource, passicon1, 20);
    }//GEN-LAST:event_passicon1MouseClicked

    private void campoConFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoConFocusGained
               if(campointento ==0){
                                 campoCon.setText("");
                                 campointento=1;

     }

    }//GEN-LAST:event_campoConFocusGained
    private void limpiar(){
        btnempresa.setSelected(false);
        btnpersona.setSelected(false);
        
        txtdni.setText("");
        txtUsuario.setText("");
        txtCorreo.setText("");
        txtnum.setText("");
        campoCon.setText("");
        campoCon2.setText("");
        juser.setText("");
        jred.setText("");
        jLabel1.setText("");

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String nombre,apellido,usuario,correo,contra,contra2;
        nombre=txtdni.getText();
        usuario=txtUsuario.getText();
        contra=campoCon.getText();
        contra2=campoCon2.getText();
        correo=txtCorreo.getText();
      String numero=txtnum.getText();
        String numeroString = "51" +numero;
        String dni=txtdni.getText();         
                                            daoUsuario X=new daoUsuario();
                                              Usuario u=new Usuario();
                                              empleador e=new empleador();
                 if(!tipo.equals("")){
                     if (!nombre.isEmpty() && !dni.isEmpty() && !usuario.isEmpty() &&
                        !contra.isEmpty() && !correo.isEmpty() && 
                        !numero.isEmpty()) {
                        
                                   if(validacion==1){
                                   if(numeroString.length() == 11){
                                       if(esNumeroEntero(numero)){

                                            if(tipo.equals("Persona")){
                                                e.setFk_codiTipoEmpl("20");
                                                e.setNombEmpl(nombre);
                                            }else{
                                            if(validarletra(nombre)==true ){
                                                e.setFk_codiTipoEmpl("10");
                                                e.setNombEmpl(nombre);

                                            }else{
                                                System.out.println("INGRESAR SOLO LETRAS PARA EL NOMBRE"); 
                                            }  
                                           }                                               
                                                u.setCodiUsua(usuario);
                                                u.setPassUsua(contra);
                                                u.setTipoUsua("cliente");
                                                e.setCodiEmpl(X.generarCodigoEspecialidad() );
                                                e.setDniRucEmpl(dni);
                                                e.setEmailEmpl(correo);
                                                e.setFk_codiUsua(usuario);
                                                e.setTeleEmpl(numeroString);

                                                X.crearUsuario(u, e);
                                      
                                                                              limpiar();


                                       }else{
                                      JOptionPane.showMessageDialog(null, "NUMERO DEBE SER NUMERS");
  
                                       }
                                   }else{
                                       JOptionPane.showMessageDialog(null, "NUMERO DEBE SER NUEVO DIGITOS");

                                   }
     

                               }   else{
                                JOptionPane.showMessageDialog(null, "USUARIO YA EXISTENTE");
 
                               }
                            
                    }else{
                   JOptionPane.showMessageDialog(null,"Todos los campos deben estar completos");

                    } 
                 }else{
                                               JOptionPane.showMessageDialog(null,"SELECCIONE UN TIPO DE CUENTA");
   
                 }                          
                               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyReleased
                             String nombreuser= txtUsuario.getText();

        if(nombreuser.equals("")){
                      juser.setText("");

      }else{
        if(usuarioverificar(nombreuser)==true){
            juser.setText("NOMBRE USUARIO YA EXISTE");
            juser.setForeground(Color.RED);
            validacion=2;

        }else{
            juser.setText("NOMBRE USUARIO VALIDO");
            Color verdeOscuro = new Color(0, 128, 0);
            juser.setForeground(verdeOscuro);
               validacion=1;
        }  
      }
        
        
    }//GEN-LAST:event_txtUsuarioKeyReleased

    private void campoConKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoConKeyReleased
        // TODO add your handling code here:
               String contra,contra2;
       contra=campoCon.getText();
       contra2=campoCon2.getText(); 

        
    if (contra.equals(contra2)) {
        jred.setText(""); // Contraseñas coinciden, no hay mensaje de error
    } else {
        jred.setText("CONTRASEÑA NO SON IGUALES"); // Contraseñas no coinciden
    }
      
    }//GEN-LAST:event_campoConKeyReleased

    private void campoCon2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCon2FocusGained
               if(campointento2 ==0){
                                 campoCon2.setText("");
                                 campointento2=1;

     }        // TODO add your handling code here:
    }//GEN-LAST:event_campoCon2FocusGained

    private void campoCon2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCon2KeyReleased
        // TODO add your handling code here:
                       String contra,contra2;
       contra=campoCon.getText();
       contra2=campoCon2.getText(); 

        
    if (contra.equals(contra2)) {
        jred.setText(""); // Contraseñas coinciden, no hay mensaje de error
    } else {
        jred.setText("CONTRASEÑA NO SON IGUALES"); // Contraseñas no coinciden
    }
    }//GEN-LAST:event_campoCon2KeyReleased

    private void txtnumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumKeyReleased
             
        int X=txtnum.getText().length();
        if(X==9){
            jLabel1.setText("NUMERO VALIDO");
            Color verdeOscuro = new Color(0, 128, 0);
            jLabel1.setForeground(verdeOscuro);

        }else{
            jLabel1.setForeground(Color.red);
            jLabel1.setText("NUMERO NO VALIDO");
            jLabel1.setForeground(Color.RED);

        }
        if(X>9){
         txtnum.setText(txtnum.getText().substring(0, 9));
        jLabel1.setText("NUMERO VALIDO");
            Color verdeOscuro = new Color(0, 128, 0);
            jLabel1.setForeground(verdeOscuro);
        }
        
    }//GEN-LAST:event_txtnumKeyReleased

    private void txtnumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumFocusGained

    private void txtnumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumFocusLost
        validarNumeroEntero();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumFocusLost
    private boolean esNumeroEntero(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
        private void validarNumeroEntero() {
        String cadena = txtnum.getText();
        if (esNumeroEntero(cadena)) {
        } else {
       JOptionPane.showMessageDialog(null, "SOLO SE DEBE INGRESAR NUMEROS");
       txtnum.setText("");
        }
    }    public boolean usuarioverificar(String usuario){
        try {
          String sql="SELECT codiUsua FROM usuario Where codiUsua=?";
          PreparedStatement ps=con.prepareStatement(sql);
          ps.setString(1, usuario);
          ResultSet rs=ps.executeQuery();
          boolean validar=rs.next();
          return validar;
        } catch (Exception e) {
            return false;
        }
    }
    public boolean validarletra(String letra){
    return letra.matches("^[a-zA-Z\\s]+$");
}
    public void imageIconCambiar(URL resource, JLabel iconoMod, int tamaño) {
        ImageIcon iconLogo = new ImageIcon(resource);
        Image image = iconLogo.getImage();
        Image imgRescalado = image.getScaledInstance(tamaño, tamaño, java.awt.Image.SCALE_SMOOTH);
        iconLogo = new ImageIcon(imgRescalado);
        iconoMod.setIcon(iconLogo);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel Contraseña1;
    private javax.swing.JLabel Contraseña2;
    private javax.swing.JSeparator Separator1;
    private javax.swing.JSeparator Separator2;
    private javax.swing.JSeparator Separator3;
    private javax.swing.JSeparator Separator4;
    private javax.swing.JSeparator Separator6;
    private javax.swing.JSeparator Separator8;
    private javax.swing.JRadioButton btnempresa;
    private javax.swing.JRadioButton btnpersona;
    private javax.swing.JPasswordField campoCon;
    private javax.swing.JPasswordField campoCon2;
    private javax.swing.JLabel errorCon;
    private javax.swing.JLabel errorCon1;
    private guiRecursos.GuiBarraVentana guiBarraVentana1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jred;
    private javax.swing.JLabel juser;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblApellido2;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lbltipo;
    private javax.swing.JLabel passicon;
    private javax.swing.JLabel passicon1;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtnum;
    // End of variables declaration//GEN-END:variables
}
