package vista;

import com.formdev.flatlaf.FlatLightLaf;
import dao.ContratoDao;
import dao.EmpleadorDao;
import dao.daoTrabajador;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.ContratoDto;
import modelo.EmpleadorDto;
import modelo.Trabajador;
import modelo.Usuario;

/**
 *
 * @author Nelson
 */
public class trabajadorSolicitudes extends javax.swing.JPanel {
    EmpleadorDao daoEmp = new EmpleadorDao();
    ContratoDao daoCont = new ContratoDao();
    daoTrabajador daoTrab = new daoTrabajador();
    /**
     * Creates new form trabajadorSolicitudes
     */
    public trabajadorSolicitudes(Usuario user) {
        FlatLightLaf.setup();
        
        String CodiTrab = daoTrab.obtenerTrabajadorPorIDUsuario(user.getCodiUsua()).getCodiTrab();
        initComponents();
        generarTabla(CodiTrab);
    }

    public void generarTabla(String CodiTrab){
        List<ContratoDto> contratos = daoCont.listarContXTrabajador(CodiTrab);
        // Mostrar la lista de contratos en el JTable
        DefaultTableModel model = (DefaultTableModel) tablaContratos.getModel();
        model.setRowCount(0);
        for (ContratoDto contrato : contratos) {
            EmpleadorDto e= daoEmp.obtenerEmpleadorPorID(contrato.getCodiEmpl());
            model.addRow(new Object[]{
                contrato.getCodiCont(),
                e.getNombEmpl(),
                e.getTeleEmp(),
                contrato.getEstCont(),
                contrato.getFechCont(),
                contrato.getFechInicCont(),
                contrato.getFechFincont()
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaContratos = new javax.swing.JTable();

        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Historial");
        Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 400, 40));

        jLabel2.setText("Aquí, el cliente puede ver un historial de todas las contrataciones pasadas, asi como las negociaciones");
        Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 840, 20));

        tablaContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Telefono", "Estado", "Fecha Contrato", "Fecha Inicio", "Fecha Final"
            }
        ));
        jScrollPane1.setViewportView(tablaContratos);

        Panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 908, 164));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaContratos;
    // End of variables declaration//GEN-END:variables
}
